import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import enUi from './locales/en/ui.json';
import enCards from './locales/en/cards.json';
import enCardNames from './locales/en/cardNames.json';
import enPokemonNames from './locales/en/pokemonNames.json';
import frUi from './locales/fr/ui.json';
import frCards from './locales/fr/cards.json';
import frCardNames from './locales/fr/cardNames.json';
import frPokemonNames from './locales/fr/pokemonNames.json';

export const SUPPORTED_LANGUAGES = ['en', 'fr'] as const;
export type Language = (typeof SUPPORTED_LANGUAGES)[number];

/**
 * Four namespaces so the growing content pool stays manageable:
 *   - `ui`            → screen / menu / button strings (also the default).
 *   - `cards`         → effect-line templates, kinds, statuses, weather.
 *   - `cardNames`     → one entry per card.
 *   - `pokemonNames`  → one entry per species (keyed by `speciesSlug`). Auto-generated by
 *                       `npm run fetch-pokedex` from PokéAPI's localized names.
 * Adding a 300th card costs one line in `cardNames.json` and zero in the other three.
 */
void i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en: { ui: enUi, cards: enCards, cardNames: enCardNames, pokemonNames: enPokemonNames },
      fr: { ui: frUi, cards: frCards, cardNames: frCardNames, pokemonNames: frPokemonNames },
    },
    ns: ['ui', 'cards', 'cardNames', 'pokemonNames'],
    defaultNS: 'ui',
    fallbackLng: 'en',
    supportedLngs: SUPPORTED_LANGUAGES,
    interpolation: { escapeValue: false },
    detection: {
      order: ['localStorage', 'navigator'],
      lookupLocalStorage: 'pokespire-lang',
      caches: ['localStorage'],
    },
  });

export default i18n;
